language: generic
env:
  global:
    - JS_SCRIPT_PATH=_scripts
jobs:
  include:
    - stage: deploy
      language: node_js
      node_js:
        - "7"
      script:
        - KOBITON_USERNAME=$KOBITON_USERNAME KOBITON_API_KEY=$KOBITON_API_KEY node $JS_SCRIPT_PATH/upload-app.js apps/ContactManager.apk ContactManager.apk
branches:
  only:
    - node
