language: generic
env:
  global:
    - JS_SCRIPT_PATH=_scripts
    - TEST_APP_PATH=bkp/app
jobs:
  include:
    - stage: deploy
      language: node_js
      node_js:
        - "7"
      script:
        - npm install request
        - node $JS_SCRIPT_PATH/upload-app.js $TEST_APP_PATH/app.apk app.apk
branches:
  only:
    - node
