language: generic
env:
  global:
    - BUILD_TEST=cloud/docker
    - PROJECT_TEST=odroidfeeder
jobs:
  include:
    - stage: test
      script:
        - cd $BUILD_TEST
        - bash build-test.sh $PROJECT_TEST

branches:
  only:
    - develop
