language: generic

env:
  global:
    - BUILD_TEST=cloud/docker
    - PROJECT_TEST=odroidfeeder
    - JS_SCRIPT_PATH=_scripts
    - TEST_APP_PATH=bkp/app
    - DELIVERED_APP_PATH=$TRAVIS_BUILD_DIR/$PROJECT_TEST/build/app/outputs/apk/release/
    
cache:
  directories:
    - $DELIVERED_APP_PATH
    
jobs:
  include:
  
    - stage: test
      script:
        - bash $BUILD_TEST/build-test.sh $PROJECT_TEST
        
    - stage: build
      script:
        - bash $BUILD_TEST/build-test.sh $PROJECT_TEST build
        - ls $DELIVERED_APP_PATH

    - stage: deploy
      language: node_js
      node_js:
        - "7"
      before_script:
        - bash $BUILD_TEST/build-test.sh $PROJECT_TEST deploy
        - npm install request
      script:
        - node $JS_SCRIPT_PATH/upload-app.js ${DELIVERED_APP_PATH}app-release.apk $TRAVIS_BUILD_NUMBER-app-release.apk
        
branches:
  only:
    - develop
