language: generic
env:
  global:
    - BUILD_TEST=cloud/docker
    - PROJECT_TEST=odroidfeeder
    - JS_SCRIPT_PATH=_scripts
    - TEST_APP_PATH=bkp/app
    - DELIVERED_APP_PATH=build/app/outputs/apk/
jobs:
  include:
    - stage: test
      script:
        - cd $BUILD_TEST
        - bash build-test.sh $PROJECT_TEST
    - stage: build
      script:
        - cd $BUILD_TEST
        - bash build-test.sh $PROJECT_TEST build

    - stage: deploy
      language: node_js
      node_js:
        - "7"
      before_script:
        - npm install request
      script:
        - node $JS_SCRIPT_PATH/upload-app.js $DELIVERED_APP_PATH/app.apk $TRAVIS_BUILD_NUMBER-app.apk
branches:
  only:
    - node
